In [2]:
import nrrd

In [1]:
import numpy as np

In [3]:
data, header = nrrd.read("cube.nrrd")
mat = np.append(header['space directions'], header['space origin'][:, np.newaxis], axis=1)
ItoW = np.append(mat, [[0, 0, 0, 1]], axis=0)
display(mat)
display(ItoW)

array([[ 0.08      ,  0.        ,  0.        , -1.95999992],
       [ 0.        ,  0.05714286,  0.        , -1.97142863],
       [ 0.        ,  0.        ,  0.04444445, -1.97777784]])

array([[ 0.08      ,  0.        ,  0.        , -1.95999992],
       [ 0.        ,  0.05714286,  0.        , -1.97142863],
       [ 0.        ,  0.        ,  0.04444445, -1.97777784],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [4]:
data.shape

(50, 70, 90)

In [5]:
data = data.astype('float64')
ItoW = ItoW.astype('float64')

In [13]:
np.save('cube.npy', data)

In [14]:
np.save('cube-meta.npy',ItoW)

In [7]:
data, header = nrrd.read("cube-luta.nrrd")
data = data.astype('float64')

In [9]:
data.shape

(4, 300)

In [8]:
np.save('cube-luta.npy', data)

In [3]:
t = np.arange(27)
q = t.reshape(3,3,3).astype('float64')
q

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.]],

       [[ 9., 10., 11.],
        [12., 13., 14.],
        [15., 16., 17.]],

       [[18., 19., 20.],
        [21., 22., 23.],
        [24., 25., 26.]]])

In [4]:
np.save('test-cube.npy', q)